### ISSUE TITLE
How to custom Siderbar links title and form fields name?

### ISSUE THREAD

**Issue by hitobias** [TrestleAdmin/trestle-auth#20]
First, thanks for your hard work. My question is how to custom the sider bar links title and form fields label? I'm use traditional Chinese, my customer need Chinese character.

**Comment by sudoaza** [comment]
Like this you edit the menu link in the app/admin/auth/user_admin.rb or whatever name you have

```
Trestle.resource(:users, model: User, scope: Auth) do
  menu do
    group :configuration, priority: :last do
      item :users, icon: "fa fa-users", label: "Not Users"
    end
  end
```

**Comment by spohlenz** [comment]
Another option is to edit your locale files (e.g. `config/locales/zh-CN.yml`).

The relevant i18n keys are:

* Item: `admin.navigation.items.#{name}`
* Group: `admin.navigation.groups.#{name}`

So with an example block defined as:

```ruby
group :configuration, priority: :last do
  item :users, icon: "fa fa-users"
end
```

Your locale file might look like:

```yml
en:
  admin:
    navigation:
      items:
        users: My Users
     
      groups:
        configuration: My Configuration
```
